language: node_js
node_js:
   - "6.*"

branches:
  only:
    - master

before_script:
    - npm run bundle

script:
    - npm run test:ci

after_success:
    - SAUCELABS=true npm run test:browser
    - npm run test:coverage:coveralls-report

cache:
  directories:
    - node_modules

notifications:
    email: false

sudo: false
